-- AlterTable ModelPrediction
ALTER TABLE "model_predictions" DROP COLUMN IF EXISTS "entity_type",
DROP COLUMN IF EXISTS "entity_id",
DROP COLUMN IF EXISTS "prediction",
ADD COLUMN IF NOT EXISTS "investigation_id" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "finding_id" TEXT,
ADD COLUMN IF NOT EXISTS "scenario_id" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "deployment_status" TEXT NOT NULL DEFAULT 'EXPERIMENTAL_NOT_APPROVED',
ADD COLUMN IF NOT EXISTS "threshold" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS "predicted_delayed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "risk_level" TEXT NOT NULL DEFAULT 'LOW';
